[package]
name = "scalar-tofnd"
version = "0.0.0"
license = "Apache-2.0"
authors = ["huongcodelight <huong@codelight.co>"]
description = "A Scalar tss tofnd crate"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
anyhow.workspace = true
scalar-tss.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
rand.workspace = true
clap = {version = "3.0", default-features = false, features = ["std", "cargo", "env"]}
dirs = { version = "4.0", default-features = false }

# logging
tracing.workspace = true
tracing-subscriber= {version = "0.3", features = ["json", "env-filter"]}
atty = {version = "0.2", default-features = false}

# enable logging for tests
tracing-test = {version = "0.2", default-features = false}