# Consensus config
validator_configs:
  address: /ip4/127.0.0.1/tcp/8083/http
  db-path: /scalar/db/consensus_db
  internal-worker-address: null
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 1000ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/33291/http
    network_admin_server:
      primary_network_admin_server_port: 41303
      worker_network_admin_server_base_port: 41669
  protocol: narwhal
  
