[package]
name = "scalar-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Scalar validator node implementation"
default-run = "scalar-validator"

[lints]
workspace = true

[dependencies]
# scalar
reth-rpc-types.workspace = true
reth-rpc-api.workspace = true
scalar-rpc.workspace = true
# tracing
tracing = "0.1.0"

# io
fdlimit = "0.3.0"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false }
#config
confy = "0.6"
toml = "0.8"

# metrics
metrics-process = "=1.0.14"

# test vectors generation
proptest = "1.4"
rand = "0.8.5"

# tui
comfy-table = "7.0"
crossterm = "0.27.0"
ratatui = "0.25.0"
human_bytes = "0.4.1"

# async
tokio = { version = "1.21", features = ["sync", "macros", "time", "rt-multi-thread"] }
futures = "0.3.26"

# misc
aquamarine = "0.5"
eyre = "0.6"
clap = { version = "4", features = ["derive"] }
tempfile = "3.8"
backon = "0.4"
similar-asserts = "1.5.0"
rayon = "1.7"
itertools = "0.12"
boyer-moore-magiclen = "0.2.16"

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
jsonrpsee.workspace = true
assert_matches = "1.5.0"

[features]
default = ["jemalloc"]

#asm-keccak = ["reth-primitives/asm-keccak"]

#jemalloc = ["dep:jemallocator", "reth-node-core/jemalloc"]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

optimism = [
#    "reth-primitives/optimism",
#    "reth-revm/optimism",
#    "reth-interfaces/optimism",
#    "reth-rpc/optimism",
#    "reth-rpc-engine-api/optimism",
#    "reth-transaction-pool/optimism",
#    "reth-provider/optimism",
#    "reth-beacon-consensus/optimism",
#    "reth-auto-seal-consensus/optimism",
#    "reth-network/optimism",
#    "reth-network-api/optimism",
#    "reth-blockchain-tree/optimism",
#    "reth-payload-builder/optimism",
#    "reth-optimism-payload-builder/optimism",
#    "dep:reth-node-optimism",
#    "reth-node-core/optimism",
]

# no-op feature flag for switching between the `optimism` and default functionality in CI matrices
ethereum = []

[[bin]]
name = "scalar-validator"
path = "src/main.rs"

