version: "3.9"
services:
  geth:
    build:
      context: ../go-ethereum
      dockerfile: ./Dockerfile
    image: geth-client
    #image: ethereum/client-go
    container_name: geth-client
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303/tcp"
      - "30303:30303/udp"
