version: "3.9"

services:
  reth:
    image: scalar-runner
    container_name: scalar-reth
    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG=true
      - RUST_LOG=info
      # don't use debug, it generates volumes of data.
    env_file:
      - ../configs/reth/.env
    restart: unless-stopped
    volumes:
      - ../configs/reth:/reth
      - ../scripts/entry.sh:/entry.sh
    # ports:
    #   - "${PEER_PORT}:30303" # Peering ports
    #   - "${PEER_PORT}:30303/udp" # Peering ports
    #   - "${RPC_HTTP_PORT}:8545" # http
    #   - "${RPC_WS_PORT}:8546" # ws
    #   - "${PROMETHEUS_PORT}:9001" # Metrics

  validator:
    image: scalar-runner
    container_name: scalar-validator
    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG=true
      - RUST_LOG=info
      # don't use debug, it generates volumes of data.
    env_file:
      - ../configs/scalar/.env
    restart: unless-stopped
    entrypoint: ["/entry.sh", "start_validator"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "validator.scalar.org:host-gateway"
    volumes:
      - ../scripts/entry.sh:/entry.sh
    # ports:
    #   - "${CONSENSUS_JSON_RPC_PORT}:8083"
    #   - "${CONSENSUS_METRICS_PORT}:9184"
    #   - "${CONSENSUS_NETWORK_PORT}:8080" # Consensus grpc port
    #   - "${CONSENSUS_P2P_PORT}:8084" # P2p port
    #   - "${CONSENSUS_PROMETHEUS_PORT}:33291"
