version: "3.9"

services:
  reth_execution:
    image: scalar-reth
    container_name: scalar-reth-${NODE_NAME}
    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG=true
      - RUST_LOG=info
      # don't use debug, it generates volumes of data.
    env_file:
      - ../configs/reth/.env
    restart: unless-stopped
    volumes:
      - ../configs/reth:/reth
      - ../scripts/entry.sh:/entry.sh
    ports:
      - "${PEER_PORT}:30303" # Peering ports
      - "${PEER_PORT}:30303/udp" # Peering ports
      - "${RPC_HTTP_PORT}:8545" # http
      - "${RPC_HTTP_PORT}:8546" # ws
      - "${PROMETHEUS_PORT}:9001" # Metrics

  validator:
    image: scalar-validator
    container_name: scalar-validator-${NODE_NAME}
    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG=true
      - RUST_LOG=info
      # don't use debug, it generates volumes of data.
    env_file:
      - ../configs/scalar/.env
    restart: unless-stopped
    volumes:
      - ../configs/scalar:/scalar
      - ../scripts/entry.sh:/entry.sh
    ports:
      - "CONSENSUS_SERVICE_PORT:9090" # Consensus grpc port

