version: "3.9"
networks:
  scalar_evmos:
    ipam:
      config:
        - subnet: 172.22.0.0/24
services:
  scalar-abci1:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-abci1
    ports:
      - "26617:26657"
    env_file:
      - ../runtime/node1/abci/.env
    volumes:
      - ../runtime/node1/abci:/opt/abci
    command: ["/scripts/start-abci.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.11"

  scalar-abci2:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-abci2
    ports:
      - "26627:26657"
    env_file:
      - ../runtime/node2/abci/.env
    volumes:
      - ../runtime/node2/abci:/opt/abci
    command: ["/scripts/start-abci.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.12"

  scalar-abci3:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-abci3
    ports:
      - "26637:26657"
    env_file:
      - ../runtime/node3/abci/.env
    volumes:
      - ../runtime/node3/abci:/opt/abci
    command: ["/scripts/start-abci.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.13"

  scalar-abci4:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-abci4
    ports:
      - "26647:26657"
    env_file:
      - ../runtime/node4/abci/.env
    volumes:
      - ../runtime/node4/abci:/opt/abci
    command: ["/scripts/start-abci.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.14"

  scalar-tendermint1:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-tendermint1
    ports:
      - "26616:26656"
    env_file:
      - ../runtime/node1/tendermint/.env
      - ../runtime/tendermint/seeds/scalartendermint1
    volumes:
      - ../runtime/node1/tendermint:/opt/tendermint
      - ../runtime/tendermint/seeds:/opt/seeds
    command: ["/scripts/start-tendermint.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.21"

  scalar-tendermint2:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-tendermint2
    ports:
      - "26626:26656"
    env_file:
      - ../runtime/node2/tendermint/.env
      - ../runtime/tendermint/seeds/scalartendermint2
    volumes:
      - ../runtime/node2/tendermint:/opt/tendermint
      - ../runtime/tendermint/seeds:/opt/seeds
    command: ["/scripts/start-tendermint.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.22"

  scalar-tendermint3:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-tendermint3
    ports:
      - "26636:26656"
    env_file:
      - ../runtime/node3/tendermint/.env
      - ../runtime/tendermint/seeds/scalartendermint3
    volumes:
      - ../runtime/node3/tendermint:/opt/tendermint
      - ../runtime/tendermint/seeds:/opt/seeds
    command: ["/scripts/start-tendermint.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.23"

  scalar-tendermint4:
    extends:
      file: ./docker-compose-evmos.yaml
      service: scalar-evmos
    container_name: scalar-tendermint4
    ports:
      - "26646:26656"
    env_file:
      - ../runtime/node4/tendermint/.env
      - ../runtime/tendermint/seeds/scalartendermint4
    volumes:
      - ../runtime/node4/tendermint:/opt/tendermint
      - ../runtime/tendermint/seeds:/opt/seeds
    command: ["/scripts/start-tendermint.sh"]
    networks:
      scalar_evmos:
        ipv4_address: "172.22.0.24"
