version: "3.9"
networks:
  scalar_dev:
    ipam:
      config:
        - subnet: 172.21.0.0/24
  scalar_test:
    driver: "bridge"
services:
  validator_genesis:
    extends:
      file: ./docker-runner.yaml
      service: validator
    restart: "no"
    container_name: validator_genesis
    volumes:
      - ${RUNTIME}/genesis/scalar:/opt/scalar
      - ${ROOT}/docker/genesis.yaml:/opt/scalar/genesis.yaml
    environment:
      - SUI_CONFIG_DIR=/opt/scalar/config
    #entrypoint: ["/entry.sh", "init_validators"]
    entrypoint: ["sleep", "infinity"]

  validator1:
    extends:
      file: ./docker-runner.yaml
      service: validator
    container_name: validator1
    depends_on:
      - validator_genesis
    ports:
      - "${NODE1_CONSENSUS_JSON_RPC_PORT}:8083"
      - "${NODE1_CONSENSUS_METRICS_PORT}:9184"
      - "${NODE1_CONSENSUS_NETWORK_PORT}:8080" # Consensus grpc port
      - "${NODE1_CONSENSUS_P2P_PORT}:8084" # P2p port
      - "${NODE1_CONSENSUS_PROMETHEUS_PORT}:33291"
    volumes:
      - ${RUNTIME}/node1/scalar:/opt/scalar
      - ${RUNTIME}/genesis/scalar/config/genesis.blob:/opt/scalar/config/genesis.blob
      - ${RUNTIME}/genesis/scalar/config/validator1-8080.yaml:/opt/scalar/config/validator.yaml
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_VALIDATOR1}

  reth1:
    extends:
      file: ./docker-runner.yaml
      service: reth
    container_name: reth1
    # entrypoint: ["/entry.sh", "scalar_reth_mvp"]
    entrypoint: ["/entry.sh", "scalar_eth_server"]
    ports:
      - "${NODE1_RETH_PEER_PORT}:30303" # Peering ports
      - "${NODE1_RETH_PEER_PORT}:30303/udp" # Peering ports
      - "${NODE1_RETH_RPC_HTTP_PORT}:8545" # http
      - "${NODE1_RETH_RPC_WS_PORT}:8546" # ws
      - "${NODE1_RETH_PROMETHEUS_PORT}:9001" # Metrics
    env_file:
      - ${RUNTIME}/node1/reth/.env
    volumes:
      - ${RUNTIME}/node1/reth:/opt/reth
      - ${ROOT}/docker/genesis/reth/genesis.json:/opt/reth/genesis.json
    networks:
      scalar_dev:
        ipv4_address: "${IPV4_ADDRESS_RETH1}"

  validator2:
    extends:
      file: ./docker-runner.yaml
      service: validator
    container_name: validator2
    depends_on:
      - validator_genesis
    ports:
      - "${NODE2_CONSENSUS_JSON_RPC_PORT}:8083"
      - "${NODE2_CONSENSUS_METRICS_PORT}:9184"
      - "${NODE2_CONSENSUS_NETWORK_PORT}:8080" # Consensus grpc port
      - "${NODE2_CONSENSUS_P2P_PORT}:8084" # P2p port
      - "${NODE2_CONSENSUS_PROMETHEUS_PORT}:33291"
    volumes:
      - ${RUNTIME}/node2/scalar:/opt/scalar/config
      - ${RUNTIME}/genesis/scalar/config/genesis.blob:/opt/scalar/config/genesis.blob
      - ${RUNTIME}/genesis/scalar/config/validator2-8080.yaml:/opt/scalar/config/validator.yaml
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_VALIDATOR2}

  reth2:
    extends:
      file: ./docker-runner.yaml
      service: reth
    container_name: reth2
    # entrypoint: ["/entry.sh", "scalar_reth_mvp"]
    entrypoint: ["/entry.sh", "scalar_eth_server"]
    ports:
      - "${NODE2_RETH_PEER_PORT}:30303" # Peering ports
      - "${NODE2_RETH_PEER_PORT}:30303/udp" # Peering ports
      - "${NODE2_RETH_RPC_HTTP_PORT}:8545" # http
      - "${NODE2_RETH_RPC_WS_PORT}:8546" # ws
      - "${NODE2_RETH_PROMETHEUS_PORT}:9001" # Metrics
    env_file:
      - ${RUNTIME}/node2/reth/.env
    volumes:
      - ${RUNTIME}/node2/reth:/opt/reth
      - ${ROOT}/docker/genesis/reth/genesis.json:/opt/reth/genesis.json
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_RETH2}

  validator3:
    extends:
      file: ./docker-runner.yaml
      service: validator
    container_name: validator3
    depends_on:
      - validator_genesis
    ports:
      - "${NODE3_CONSENSUS_JSON_RPC_PORT}:8083"
      - "${NODE3_CONSENSUS_METRICS_PORT}:9184"
      - "${NODE3_CONSENSUS_NETWORK_PORT}:8080" # Consensus grpc port
      - "${NODE3_CONSENSUS_P2P_PORT}:8084" # P2p port
      - "${NODE3_CONSENSUS_PROMETHEUS_PORT}:33291"
    volumes:
      - ${RUNTIME}/node3/scalar:/opt/scalar/config
      - ${RUNTIME}/genesis/scalar/config/genesis.blob:/opt/scalar/config/genesis.blob
      - ${RUNTIME}/genesis/scalar/config/validator3-8080.yaml:/opt/scalar/config/validator.yaml
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_VALIDATOR3}

  reth3:
    extends:
      file: ./docker-runner.yaml
      service: reth
    container_name: reth3
    # entrypoint: ["/entry.sh", "scalar_reth_mvp"]
    entrypoint: ["/entry.sh", "scalar_eth_server"]
    ports:
      - "${NODE3_RETH_PEER_PORT}:30303" # Peering ports
      - "${NODE3_RETH_PEER_PORT}:30303/udp" # Peering ports
      - "${NODE3_RETH_RPC_HTTP_PORT}:8545" # http
      - "${NODE3_RETH_RPC_WS_PORT}:8546" # ws
      - "${NODE3_RETH_PROMETHEUS_PORT}:9001" # Metrics
    env_file:
      - ${RUNTIME}/node3/reth/.env
    volumes:
      - ${RUNTIME}/node3/reth:/opt/reth
      - ${ROOT}/docker/genesis/reth/genesis.json:/opt/reth/genesis.json
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_RETH3}

  validator4:
    extends:
      file: ./docker-runner.yaml
      service: validator
    container_name: validator4
    depends_on:
      - validator_genesis
    ports:
      - "${NODE4_CONSENSUS_JSON_RPC_PORT}:8083"
      - "${NODE4_CONSENSUS_METRICS_PORT}:9184"
      - "${NODE4_CONSENSUS_NETWORK_PORT}:8080" # Consensus grpc port
      - "${NODE4_CONSENSUS_P2P_PORT}:8084" # P2p port
      - "${NODE4_CONSENSUS_PROMETHEUS_PORT}:33291"
    volumes:
      - ${RUNTIME}/node4/scalar:/opt/scalar/config
      - ${RUNTIME}/genesis/scalar/config/genesis.blob:/opt/scalar/config/genesis.blob
      - ${RUNTIME}/genesis/scalar/config/validator4-8080.yaml:/opt/scalar/config/validator.yaml
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_VALIDATOR4}

  reth4:
    extends:
      file: ./docker-runner.yaml
      service: reth
    container_name: reth4
    # entrypoint: ["/entry.sh", "scalar_reth_mvp"]
    entrypoint: ["/entry.sh", "scalar_eth_server"]
    ports:
      - "${NODE4_RETH_PEER_PORT}:30303" # Peering ports
      - "${NODE4_RETH_PEER_PORT}:30303/udp" # Peering ports
      - "${NODE4_RETH_RPC_HTTP_PORT}:8545" # http
      - "${NODE4_RETH_RPC_WS_PORT}:8546" # ws
      - "${NODE4_RETH_PROMETHEUS_PORT}:9001" # Metrics
    env_file:
      - ${RUNTIME}/node4/reth/.env
    volumes:
      - ${RUNTIME}/node4/reth:/opt/reth
      - ${ROOT}/docker/genesis/reth/genesis.json:/opt/reth/genesis.json
    networks:
      scalar_dev:
        ipv4_address: ${IPV4_ADDRESS_RETH4}
