[package]
name = "scalar-types"
version = "0.1.0"
authors = ["Codelight <tai@scalar.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
byteorder.workspace = true
derive_more.workspace = true
enum_dispatch.workspace = true
eyre.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
fastcrypto-zkp.workspace = true
hex.workspace = true
im.workspace = true
indexmap.workspace = true
itertools.workspace = true
once_cell.workspace = true
primitive-types.workspace = true
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand.workspace = true
roaring.workspace = true
serde.workspace = true
serde-name.workspace = true
serde_json.workspace = true
serde_with.workspace = true
schemars.workspace = true
shared-crypto.workspace = true
static_assertions.workspace = true
strum.workspace = true
strum_macros.workspace = true

sui-protocol-config.workspace = true
tap.workspace = true
typed-store.workspace = true
thiserror.workspace = true
tonic.workspace = true
tracing.workspace = true

mysten-metrics.workspace = true
mysten-network.workspace = true
narwhal-crypto.workspace = true
sui-macros.workspace = true
num.workspace = true
uint.workspace = true

#For move
ref-cast.workspace = true
ethnum.workspace = true
arbitrary.workspace = true
