[package]
name = "scalar-consensus-adapter-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
prost.workspace = true
tonic.workspace = true

# misc
# cfg-if = "1.0.0"

# [dev-dependencies]
# assert_matches.workspace = true
# mockall = "0.11.3"

[build-dependencies]
tonic-build.workspace = true
