[package]
name = "scalar-narwhal-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
eyre.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
reth-consensus-common = { path = "../common" }
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-stages = { path = "../../stages" }
reth-db.workspace = true
reth-provider.workspace = true
reth-rpc = { path = "../../rpc/rpc" }
reth-rpc-types.workspace = true
reth-tasks.workspace = true
reth-payload-builder.workspace = true
reth-prune = { path = "../../prune" }
reth-snapshot = { path = "../../snapshot" }
reth-rpc-types-compat.workspace = true
reth-tokio-util.workspace = true
reth-transaction-pool.workspace = true
scalar-consensus-adapter-common = { path = "../../../crates/scalar-consensus-adapter/common" }
# async
async-stream.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures.workspace = true

tower.workspace = true
tower-http.workspace = true
# metrics
reth-metrics.workspace = true
metrics.workspace = true

# misc
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
schnellru = "0.2"
cfg-if = "1.0.0"

[dev-dependencies]
# reth
reth-payload-builder = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-stages = { path = "../../stages", features = ["test-utils"] }
reth-blockchain-tree = { path = "../../blockchain-tree", features = [
  "test-utils",
] }
reth-db = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-tracing.workspace = true
reth-revm = { path = "../../revm" }
reth-downloaders = { path = "../../net/downloaders" }

assert_matches.workspace = true

[features]
optimism = [
  "reth-consensus-common/optimism",
  "reth-primitives/optimism",
  "reth-interfaces/optimism",
  "reth-provider/optimism",
  "reth-rpc-types/optimism",
]
