[package]
name = "eth-tests"
version.workspace = true
description = "A eth test crate supports the reth rpc protocol"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
ethers = { version = "2.0", features = ["rustls"] }
# Ethers' async features rely upon the Tokio async runtime.
tokio.workspace = true
# Flexible concrete Error Reporting type built on std::error::Error with customizable Reports
eyre.workspace = true

rand.workspace = true
