[package]
name = "reth-test-cluster"
version = "0.1.0"
authors = ["Duc Huong Nguyen <huong@codelight.co>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
futures.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
clap.workspace = true
async-trait.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
telemetry-subscribers.workspace = true
derivative.workspace = true
tempfile.workspace = true
reth-cluster-test.workspace = true
ethers = { version = "2.0", features = ["rustls"] }

# env
dotenvy = { version = "0.15", default-features = false }
envy = "0.4"