[package]
name = "sui-verifier-next-vm"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-abstract-stack.workspace = true

move-bytecode-verifier = { git = "https://github.com/MystenLabs/sui", rev = "01a8af7fca6aa8d24cdafad87a1191e06ac75af8", package = "move-bytecode-verifier-next-vm" }
# move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/next-vm/crates/move-bytecode-verifier", package = "move-bytecode-verifier-next-vm" }

scalar-types.workspace = true
workspace-hack.workspace = true
